# Generated by Django 3.1.2 on 2022-05-18 05:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Augment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('rarity', models.IntegerField(null=True, verbose_name=[django.core.validators.MaxValueValidator(3)])),
                ('riot_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BasicItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('riot_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('riot_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('riot_id', models.CharField(max_length=250)),
                ('component_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_component', to='BaseData.basicitem')),
                ('component_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_component', to='BaseData.basicitem')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('riot_id', models.CharField(max_length=250)),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('traits', models.ManyToManyField(to='BaseData.Traits')),
            ],
        ),
    ]
