# Generated by Django 3.1.2 on 2022-05-18 05:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemizedUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('star_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseData.champion')),
                ('item_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_item', to='BaseData.item')),
                ('item_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_item', to='BaseData.item')),
                ('item_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_item', to='BaseData.item')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placement', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8)])),
                ('final_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('patch', models.CharField(default='No added', max_length=255)),
                ('tft_set_number', models.CharField(default='7', max_length=255)),
                ('augment_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_augment', to='BaseData.augment')),
                ('augment_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_augment', to='BaseData.augment')),
                ('augment_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_augment', to='BaseData.augment')),
                ('champ_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_champ', to='GameData.itemizedunit')),
                ('champ_10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenth_champ', to='GameData.itemizedunit')),
                ('champ_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_champ', to='GameData.itemizedunit')),
                ('champ_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_champ', to='GameData.itemizedunit')),
                ('champ_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_champ', to='GameData.itemizedunit')),
                ('champ_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_champ', to='GameData.itemizedunit')),
                ('champ_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixth_champ', to='GameData.itemizedunit')),
                ('champ_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seventh_champ', to='GameData.itemizedunit')),
                ('champ_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_champ', to='GameData.itemizedunit')),
                ('champ_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ninth_carry', to='GameData.itemizedunit')),
                ('first_champ', models.ForeignKey(limit_choices_to={'value': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseData.champion')),
                ('first_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseData.basicitem')),
            ],
        ),
    ]
